spring:
  data:
    mongodb:
 #     authentication-database:
 #     username: ${MONGO_USERNAME}
  #    password: ${MONGO_PASSWORD}
  #    database: ${MONGO_DATABASE}
  #    port: ${MONGO_PORT}
  #    host: ${MONGO_HOST}
       database: keepnote
       port: 27017
       host: localhost
  application:
    name: reminder-service
server:
  port: 8096

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/


#
#spring:
#  data:
#    mongodb:
# #     authentication-database:
#      username: chandan
#      password: root
#      database: reminderDb
#      port: 27017
#      host: localhost
#  application:
#    name: reminder-service
#
#server:
#  port: 8081
