spring:
  data:
    mongodb:
 #     authentication-database:
 #     username: ${MONGO_USERNAME}
  #    password: ${MONGO_PASSWORD}
  #    database: ${MONGO_DATABASE}
  #    port: ${MONGO_PORT}
  #    host: ${MONGO_HOST}
       database: dockerplugin
       port: 27017
       host: localhost
  application:
    name: dockerplugin-test-service
server:
  port: 8091  
