server:
   port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    
spring:
  application:
    name: config-server
   
