 eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
 
 ping-server:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8096,localhost:8097
    ServerListRefreshInterval: 15000 
    
  
 
        
  
 
